directory: /home/jc/Music
#plugins: chroma fetchart embedart lyrics scrub replaygain mbsync
plugins: fetchart embedart scrub replaygain mbsync

replaygain:
    backend: gstreamer

#mpdupdate:
#    host: localhost
#    port: 6600
